name: Deploy Node.js to Hostinger VPS

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies and run tests
        run: |
          npm ci
          npm run test --if-present
          npm run build --if-present
      
      - name: Deploy to Hostinger VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          envs: MONGODB_URL,CLOUD_NAME,CLOUDINARY_API_KEY,CLOUDINARY_API_KEY,CLOUDINARY_API_SECRET,JWT_KEY,ADMIN_USERNAME,ADMIN_EMAIL,ADMIN_PASSWORD,STRIPE_SECRET_KEY,STRIPE_PUBLISHABLE_KEY,STRIPE_WEBHOOK_SECRET,DESTINATION_NUMBER,SENDER_NUMBER,ACCOUNTSID,AUTHTOKEN,RESEND_API_KEY,EMAIL
          script: |
            cd /var/www/Silksoul-Backend
            
            # Create .env file with repository secrets
            cat > .env << EOF
            MONGODB_URL=${{ secrets.MONGODB_URL }}
            CLOUD_NAME=${{ secrets.CLOUD_NAME }}
            CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}
            CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}
            JWT_KEY=${{ secrets.JWT_KEY }}
            ADMIN_USERNAME=${{ secrets.ADMIN_USERNAME }}
            ADMIN_EMAIL=${{ secrets.ADMIN_EMAIL }}
            ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}
            STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}
            STRIPE_PUBLISHABLE_KEY=${{ secrets.STRIPE_PUBLISHABLE_KEY }}
            STRIPE_WEBHOOK_SECRET=${{ secrets.STRIPE_WEBHOOK_SECRET }}
            DESTINATION_NUMBER=${{ secrets.DESTINATION_NUMBER }}
            SENDER_NUMBER=${{ secrets.SENDER_NUMBER }}
            ACCOUNTSID=${{ secrets.ACCOUNTSID }}
            AUTHTOKEN=${{ secrets.AUTHTOKEN }}
            RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}
            EMAIL=${{ secrets.EMAIL }}
            EOF
            
            # Set proper permissions for .env file
            chmod 600 .env
            
            # Run deployment script
            bash ./scripts/deploy.sh